//object MustacheConstants {

    /**
     * TEMPLATING
     */

    const val COMPANY_HEADER = "company_header"
    const val AUTHOR = "author"
    const val DATE_DAY = "date_day"
    const val DATE_MONTH = "date_month"
    const val DATE_YEAR = "date_year"
    const val TABLENAME = "tableName"
    const val TABLENAME_ORIGINAL = "tableName_original"
    const val TABLENAME_LOWERCASE = "tableName_lowercase"
    const val TABLE_LABEL = "table_label"
    const val TABLENAME_CAMELCASE = "tableName_nameCamelCase"
    const val TABLENAMES = "tableNames"
    const val TABLENAMES_LAYOUT = "tableNames_layout"
    const val TABLENAMES_LAYOUT_RELATIONS = "tableNames_layout_relations"
    const val TABLENAMES_WITHOUT_MANY_TO_ONE_RELATION = "tableNames_without_many_to_one_relation"
    const val TABLENAMES_LOWERCASE = "tableNames_lowercase"
    const val TABLENAMES_NAVIGATION = "tableNames_navigation"
    const val TABLENAMES_NAVIGATION_FOR_NAVBAR = "tableNames_navigation_for_navbar"
    const val CUSTOM_FORMATTER_IMAGES = "custom_formatter_images"
    const val FIELDS = "fields"
    const val FIRST_FIELD = "first_field"
    const val FORM_FIELDS = "form_fields"
    const val APP_NAME_WITH_CAPS = "app_name_with_caps"
    const val APP_VERSION = "app_version"
    const val PACKAGE = "package"
    const val HAS_REMOTE_ADDRESS = "has_remote_address"
    const val REMOTE_ADDRESS = "remote_address"
    const val ANDROID_SDK_PATH = "android_sdk_path"
    const val CACHE_4D_SDK_PATH = "cache_4d_sdk_path"
    const val TYPES_AND_TABLES = "types_and_tables"
    const val ENTITY_CLASSES = "entity_classes"
    const val RELATIONS_MANY_TO_ONE = "relations_many_to_one"
    const val RELATIONS_ONE_TO_MANY = "relations_one_to_many"
    const val RELATIONS_EMBEDDED_RETURN_TYPE = "relations_embedded_return_type"
    const val RELATIONS = "relations"
    const val RELATIONS_DEEPLINK_ONE_TO_MANY = "relations_deeplink_one_to_many"
    const val RELATIONS_DEEPLINK_MANY_TO_ONE = "relations_deeplink_many_to_one"
    const val RELATIONS_WITHOUT_ALIAS = "relations_without_alias"
    const val RELATIONS_ID = "relations_id"
    const val TABLE_HAS_ANY_RELATION = "table_has_any_relation"
    const val HAS_ANY_MANY_TO_ONE_RELATION = "has_any_many_to_one_relation"
    const val TABLE_HAS_DATE_FIELD = "table_has_date_field"
    const val TABLE_HAS_TIME_FIELD = "table_has_time_field"
    const val TABLE_HAS_ONE_TO_MANY_FIELD = "table_has_one_to_many_field"
    const val HAS_RELATION = "has_relation"
    const val HAS_ANY_ONE_TO_MANY_RELATION = "has_any_one_to_many_relation"
    const val HAS_ANY_ONE_TO_MANY_RELATION_FOR_LAYOUT = "has_any_one_to_many_relation_for_layout"
    const val RELATIONS_ONE_TO_MANY_FOR_LIST = "relations_one_to_many_for_list"
    const val RELATIONS_MANY_TO_ONE_FOR_LIST = "relations_many_to_one_for_list"
    const val RELATIONS_ONE_TO_MANY_FOR_DETAIL = "relations_one_to_many_for_detail"
    const val RELATIONS_MANY_TO_ONE_FOR_DETAIL = "relations_many_to_one_for_detail"
    const val HAS_DATASET = "hasDataSet"
    const val PERMISSIONS = "permissions"
    const val HAS_KOTLIN_INPUT_CONTROLS_TEMPLATE = "has_kotlin_input_controls"
    const val KOTLIN_INPUT_CONTROLS = "kotlin_input_controls"
    const val HAS_CUSTOM_LOGIN = "has_custom_login"
    const val LOGIN_CLASS_NAME = "login_class_name"
    const val DEBUG_MODE = "debug_mode"
    const val SECTION_FIELDS = "section_fields"
    const val DEEPLINK = "deep_link"
    const val UNIVERSAL_LINK_WITH_BUNDLE_ID = "universal_link_with_bundle_id"
    const val UNIVERSAL_LINK_WITHOUT_BUNDLE_ID = "universal_link_without_bundle_id"
    const val DEFAULT_SORT_FIELDS = "default_sort_fields"
    const val IS_GOOGLE_MAPS_PLATFORM_USED = "isGoogleMapsPlatformUsed"
    const val IS_GOOGLE_MAPS_PLATFORM_USED_FOR_TABLE = "isGoogleMapsPlatformUsedForTable"
    const val HAS_PUSH_NOTIFICATIONS = "hasPushNotifications"
    const val BRANCH_VERSION = "branch_version"
//}
