//object ProjectEditorConstants {

    /**
     * PROJECT EDITOR JSON KEYS
     */
    const val PROJECT_KEY = "project"
    const val DATAMODEL_KEY = "dataModel"
    const val NAME_KEY = "name"
    const val PACKAGE_KEY = "package"
    const val BUNDLE_IDENTIFIER = "bundleIdentifier"
    const val VERSION = "version"
    const val EMPTY_KEY = ""
    const val LABEL_KEY = "label"
    const val KIND_KEY = "kind"
    const val FORMAT_KEY = "format"
    const val SHORTLABEL_KEY = "shortLabel"
    const val ICON_KEY = "icon"
    const val FILTER_KEY = "filter"
    const val VALIDATED_KEY = "validated"
    const val STRING_KEY = "string"
    const val FIELDTYPE_KEY = "fieldType"
    const val VALUE_TYPE_KEY = "valueType"
    const val RELATEDDATACLASS_KEY = "relatedDataClass"
    const val RELATEDTABLENUMBER_KEY = "relatedTableNumber"
    const val INVERSENAME_KEY = "inverseName"
    const val ISTOMANY_KEY = "isToMany"
    const val RELATEDENTITIES_KEY = "relatedEntities"
    const val LIST_KEY = "list"
    const val FORM_KEY = "form"
    const val SEARCHABLE_WITH_BARCODE = "searchableWithBarcode"
    const val FIELDS_KEY = "fields"
    const val ID_KEY = "id"
    const val DETAIL_KEY = "detail"
    const val MAIN_KEY = "main"
    const val ORDER_KEY = "order"
    const val DEVELOPER_KEY = "developer"
    const val PATH_KEY = "path"
    const val SDK_KEY = "sdk"
    const val COMPONENT_BUILD_KEY = "componentBuild"
    const val IDE_BUILD_VERSION_KEY = "ideBuildVersion"
    const val IDE_VERSION_KEY = "ideVersion"
    const val CACHE_4D_SDK_KEY = "cache_4d_sdk"
    const val ORGANIZATION_KEY = "organization"
    const val PRODUCT_KEY = "product"
    const val SERVER_KEY = "server"
    const val LOGIN_KEY = "login"
    const val UI_KEY = "ui"
    const val DATASOURCE_KEY = "dataSource"
    const val SOURCE_KEY = "source"
    const val DOMINANT_COLOR_KEY = "dominantColor"
    const val URLS_KEY = "urls"
    const val PRODUCTION_KEY = "production"
    const val REMOTE_URL_KEY = "remote_url"
    const val TEAMID_KEY = "teamId"
    const val AUTHENTICATION_KEY = "authentication"
    const val EMAIL_KEY = "email"
    const val SCOPE_KEY = "scope"
    const val DUMPED_STAMP_KEY = "dumpedStamp"
    const val DUMPED_TABLES_KEY = "dumpedTables"
    const val ACTIONS_KEY = "actions"
    const val DEBUG_MODE_KEY = "debugMode"
    const val LOCAL_SOURCE = "canUseLocalSource"
    const val PUSH_NOTIFICATION = "pushNotification"
    const val EXTRA_KEY = "extra"

    /**
     * TYPE STRING PARSING
     */
    const val STRING_TYPE = "String"
    const val FLOAT_TYPE = "Float"
    const val TEXT_TYPE = "Text"
    const val PHOTO_TYPE = "Photo"
    const val DATE_TYPE = "Date"
    const val BOOLEAN_TYPE = "Boolean"
    const val INT_TYPE = "Int"
    const val TIME_TYPE = "Time"
    const val EMPTY_TYPE = ""
    const val OBJECT_TYPE = "Map<String, Any>"
//}